[package]
name = "chip8"
description = "Chip-8 Interpreter"
authors = ["Michael Rivnak <rivnakm1@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
rand = "0.8.5"
rand_pcg = "0.3.1"
